# Generated by Django 4.2.5 on 2024-01-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classification', '0002_alter_image_image_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
